#!/bin/sh

dir="$HOME/.config/pcc"

launch() {
'''
	██╗    ██╗██╗   ██╗ █████╗ ██╗     
	██║    ██║██║   ██║██╔══██╗██║     
	██║ █╗ ██║██║   ██║███████║██║     (code by WUAL)          
	██║███╗██║██║   ██║██╔══██║██║     
	╚███╔███╔╝╚██████╔╝██║  ██║███████╗
	╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚══════╝
'''
}

if [[ "$1" == '-a' ]]; then
	section="all"
	python3 $HOME/.config/pcc/options/all/pcc.py
elif [[ "$1" == '--all' ]]; then
	section="all"
	python3 $HOME/.config/pcc/options/all/pcc.py
elif [[ "$1" == '--wifi' ]]; then
	section="wifi"
	python3 $HOME/.config/pcc/options/wifi/pcc.py
elif [[ "$1" == '--bluetooth' ]]; then
	section="bluetooth"
	python3 $HOME/.config/pcc/options/bluetooth/pcc.py
elif [[ "$1" == '--brightness' ]]; then
	section="brightness"
	python3 $HOME/.config/pcc/options/brightness/pcc.py
elif [[ "$1" == '--sound' ]]; then
	section="sound"
	python3 $HOME/.config/pcc/options/sound/pcc.py
elif [[ "$1" == '--lock' ]]; then
	section="lock"
	python3 $HOME/.config/pcc/options/lock/pcc.py
elif [[ "$1" == '--status' ]]; then
	section="status"
	python3 $HOME/.config/pcc/options/status/pcc.py
elif [[ "$1" == '--settings' ]]; then
	section="settings"
	python3 $HOME/.config/pcc/options/settings/pcc.py
else
	cat <<- EOF
	Usage : ./pcc --option
		
	Available Options :
	--all		--wifi		--lock			-a
	--help		--bluetooth     --status		-h
	--audio		--brightness    --settings
	EOF
fi
